name: Frontend Check

on: [ push, pull_request ]

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: './web/pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
      - name: ESlint check
        run: pnpm run lint
      - name: Build
        run: pnpm run build
